package com.github.pixelase.webproject.dataaccess.model;
// Generated 02.12.2015 21:41:29 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * WorkScope generated by hbm2java
 */
@Entity
@Table(name = "work_scope")
public class WorkScope implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private String name;
	private Integer employeesCount;
	private Set<WorkRequest> workRequests = new HashSet<WorkRequest>(0);

	public WorkScope() {
	}

	public WorkScope(int id) {
		this.id = id;
	}

	public WorkScope(int id, String name, Integer employeesCount, Set<WorkRequest> workRequests) {
		this.id = id;
		this.name = name;
		this.employeesCount = employeesCount;
		this.workRequests = workRequests;
	}

	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "employees_count")
	public Integer getEmployeesCount() {
		return this.employeesCount;
	}

	public void setEmployeesCount(Integer employeesCount) {
		this.employeesCount = employeesCount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "workScope")
	public Set<WorkRequest> getWorkRequests() {
		return this.workRequests;
	}

	public void setWorkRequests(Set<WorkRequest> workRequests) {
		this.workRequests = workRequests;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof WorkScope))
			return false;
		WorkScope other = (WorkScope) obj;
		if (id != other.id)
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "WorkScope [id=" + id + ", name=" + name + ", employeesCount=" + employeesCount + ", workRequests="
				+ workRequests + "]";
	}

}
