package com.github.pixelase.webproject.dataaccess.model;
// Generated 02.12.2015 21:41:29 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.springframework.data.domain.Persistable;

/**
 * WorkScope generated by hbm2java
 */
@Entity
@Table(name = "work_scope")
public class WorkScope implements Persistable<Integer> {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private Integer employeesCount;
	private Set<WorkRequest> workRequests = new HashSet<WorkRequest>(0);

	public WorkScope() {
		super();
	}

	public WorkScope(Integer id) {
		super();
		this.id = id;
	}

	public WorkScope(String name, Integer employeesCount) {
		super();
		this.name = name;
		this.employeesCount = employeesCount;
	}

	public WorkScope(Integer id, String name, Integer employeesCount) {
		super();
		this.id = id;
		this.name = name;
		this.employeesCount = employeesCount;
	}

	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "employees_count")
	public Integer getEmployeesCount() {
		return this.employeesCount;
	}

	public void setEmployeesCount(Integer employeesCount) {
		this.employeesCount = employeesCount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "workScope")
	public Set<WorkRequest> getWorkRequests() {
		return this.workRequests;
	}

	public void setWorkRequests(Set<WorkRequest> workRequests) {
		this.workRequests = workRequests;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof WorkScope))
			return false;
		WorkScope other = (WorkScope) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "WorkScope [id=" + id + ", name=" + name + ", employeesCount=" + employeesCount + "]";
	}

	@Override
	@Transient
	public boolean isNew() {
		return id == null;
	}

}
